services:
  chrome:
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    networks:
      - selenium-network
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=3
  firefox:
    image: selenium/node-firefox:latest
    depends_on:
      - selenium-hub
    networks:
      - selenium-network
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    networks:
      - selenium-network
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

networks:
  selenium-network: